# Bulids code into an .exe and adds it to a github release.

name: "Bulider"

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Node"
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: "Run bulid.js"
        run: "npm i && npm run bulid"
      - name: "Releaser"
        uses: softprops/action-gh-release@v1
        with:
          files: "/home/runner/work/MASTER/build/connect.exe"
          name: ${{ github.sha }}
          tag_name: "release"
      - name: "Finished" 
<<<<<<< HEAD
        run: "echo Done!"
=======
        run: "echo Done!"
>>>>>>> 2889e61d8572ce75c296c5158dfd39c584a815d5
