# This is a basic workflow to help you get started with Actions

name: "Bulider"

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "Node"
        uses: actions/setup-node@v3
      - name: "Run bulid.js"
        run: "node bulid.js"
      - name: "Releaser"
        uses: nickatnight/releases-action@v2
        with:
          branch: "main"
          message: "New release"
          tag: "Release"
      - name: "Upload Asset"
        uses: PeerXu/upload-asset@v1
        with:
         file: "/bulid/roconnect.exe"
         suffix: ".exe"
        env:
           GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
      - name: "Finished" 
        run: "Done!"
         
           
