# This is a basic workflow to help you get started with Actions

name: "Bulider"

# Controls when the workflow will run
on:
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Node"
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: "Run bulid.js"
        run: "npm i && npm run bulid"
      - name: "Releaser"
        uses: softprops/action-gh-release@v1
        with:
          files: ./bulid/connect.exe
          name: ${{ github.sha }}
          tag_name: "release"
      - name: "Finished" 
        run: "echo Done!"
         
           
