# Bulids code into an .exe and adds it to a github release.

name: "Bulider"

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Node"
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: "Run bulid.js"
        run: "npm i && npm run bulid" 
      - uses: gerred/current-time@v1.0.0
      - name: "Releaser"
        uses: softprops/action-gh-release@v1
        with:
          files: "/home/runner/work/MASTER/build/connect.exe"
          name: ${{ steps.current-time.outputs.time }}
          tag_name: "release"
      - name: "Finished" 
        run: "echo Done!"
